### ISSUE TITLE
setProgress/setMaxProgress methods need the UI thread

### ISSUE THREAD

**Issue by tbruyelle** [afollestad/material-dialogs#505]
Original `setProgress` and `setMax` methods from the `android.widget.ProgressBar` handles being invoked from another thread than the UI thread.

`MaterialDialogs.setProgress/setMaxProgress` should do the same no ?

**Comment by afollestad** [comment]
You mean ProgressDialog? ProgressBar doesn't do that, it's a view.

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.2

**Comment by tbruyelle** [comment]
No it's really the `ProgressBar` who handles being invoked from another thread. So in your `MaterialDialog` you don't have to throw an exception if you're not in the UI Thread. Just call `ProgressBar.setProgress/setMax` and it will be ok.

The only thing you have to handle is in `MaterialDialog.setProgress` where you also update the progress label and progress minmax. Ensure those `setText` are invoked in the UI Thread.

I don't get why you close the issue, I didn't see any commit about the fix. Do you mean the fix is only on the APK pushed in 6b95674b8b82c4e0278bbb60e05b0e13e9439414  ? Where is the code ?

**Comment by afollestad** [comment]
I don't throw an Exception, Android does. I solved your issue by posting to
the thread the dialog was created on.

There are not any views on Android that are threadsafe. That's not how
views work.

**Comment by tbruyelle** [comment]
> I don't throw an Exception,

? https://github.com/afollestad/material-dialogs/blob/8c78a7a1c54424ae4a2fc69d329d8bb7201ef0fc/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L1329

You still throw an exception and so your fix is not helpful. 

> There are not any views on Android that are threadsafe. That's not how
> views work.

Yeah they probably make an exception for `ProgressBar` because methods like `setProgress/setMax` are commonly used in a background thread. 

Because your `MaterialDialog` aims to mimic the `ProgressDialog`, `setProgress/setMaxProgress` should also be callable from a background thread. About the other methods of the class you shouldn't change them.

**Comment by afollestad** [comment]
Woops, forgot to remove that.

And you're right (http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.2_r1/android/widget/ProgressBar.java#ProgressBar), removed the handler usage and exception throwing for those two methods. https://github.com/afollestad/material-dialogs/commit/12b8f1d9caf4d856ed1030783456667e46a4c8f7

**Comment by tbruyelle** [comment]
Fine, you can also remove the handler usage for `setProgressMax` because `ProgressBar.setMax` handles call from background thread just like `ProgressBar.setProgress`.

About the other handler usages you added in the commit 8c78a7a1c54424ae4a2fc69d329d8bb7201ef0fc, I'm not sure they are really useful, my concern was only about `setProgress/setProgressMax`.

**Comment by afollestad** [comment]
Done in the latest commit.

The other handler usages are useful, it makes the dialog completely thread safe other than when you initially show it.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.3.3
